# -- Unbind default command prefix and add C-Space as the alternative --
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# -- Reload without exiting
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Enable mouse
set -g mouse on

# Windows index starts at 1, rather than 0
set -g base-index 1

setw -g pane-base-index 1

# Terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# New pane border style
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

# Change the defaults for switching between panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# Fix Vim delay when pressing Esc key
set -sg escape-time 0

# Change the default keys for splitting windows
bind -n C-h split-window -h
bind -n C-v split-window -v
unbind '"'
unbind %

# Vim pane resizing
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

# Kill panes in an easier way
bind -n M-x kill-pane

# Customize the gruvbox theme

set -g @gruvbox-tmux_theme "hard"  # medium | soft | Default is hard  
set -g @gruvbox-tmux_transparent 0   # 1 | 0

set -g @gruvbox-tmux_window_id_style hsquare  # hsquare | fsquare | sub | super | arabic | earabic
set -g @gruvbox-tmux_pane_id_style super      # hsquare | fsquare | sub | super | arabic | earabic
set -g @gruvbox-tmux_zoom_id_style dsquare    # hsquare | fsquare | sub | super | arabic | earabic

set -g @gruvbox-tmux_show_battery_widget 1     # 0 to disable
set -g @gruvbox-tmux_battery_name "BAT0"       # run `ls /sys/class/power_supply` to know
set -g @gruvbox-tmux_battery_low_threshold 25

# Set Gruvbox as the theme
set -g @plugin "https://gitlab.com/motaz-shokry/gruvbox-tmux"

# Load TPM
run '~/.tmux/plugins/tpm/tpm'
